GET http://localhost:5038/games

###
GET http://localhost:5038/games/3

###
POST http://localhost:5038/games
Content-Type: application/json

{
    "name": "Street Fighter III Turbo 2",
    "genreId": 1,
    "price": 9.99,
    "releaseDate": "1985-09-13"
}

###
PUT http://localhost:5038/games/1
Content-Type: application/json

{
    "name": "Street Fighter III Fight for Life",
    "genreId": 2,
    "price": 19.99,
    "releaseDate": "1985-09-13"
}

###
DELETE http://localhost:5038/games/3
